# Wire up travis
language: python

addons:
  firefox: latest

services:
  - xvfb

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.8
      env: TOXENV=lint
  allow_failures:
      - env: TOXENV=py39

install:
  - travis_retry pip install tox
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -P /tmp/ 
  - tar -xzf /tmp/geckodriver-v0.26.0-linux64.tar.gz -C /tmp/
  - rm /tmp/geckodriver-v0.26.0-linux64.tar.gz
  - sudo mv /tmp/geckodriver /usr/local/bin

script:
  - travis_retry tox

# notifications:
#   email:
#     - pyramid-checkins@lists.repoze.org
#   irc:
#     channels:
#       - "chat.freenode.net#pyramid"
