language: python
python:
  - "3.6"

addons:
  firefox: "45.0"

install: 
  - python setup.py dev
  - pip install git+https://github.com/Pylons/deform.git
  - pip install git+https://github.com/Pylons/colander.git
  - pip install "selenium<3"
  - pip install flaky

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - pserve demo.ini &

script: nosetests  --with-flaky --max-runs=4
