# Wire up travis
language: python
sudo: false

addons:
  firefox: "45.0"

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=lint

install:
  - travis_retry pip install tox

# For Selenium
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# http://stackoverflow.com/a/34703838/315168
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"

script:
  - travis_retry tox

# notifications:
#   email:
#     - pyramid-checkins@lists.repoze.org
#   irc:
#     channels:
#       - "chat.freenode.net#pyramid"
