language: python

install: 
  - python setup.py dev
  - pip install git+https://github.com/Pylons/deform.git
  - pip install git+https://github.com/Pylons/colander.git
  - pip install selenium<3

before_script:
  # setup display  
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # start deformdemo app
  - pserve demo.ini --daemon

script: nosetests
