[tool.black]
line-length = 79
skip-string-normalization = true
py36 = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.tox
    | deformdemo\.egg-info
    | dist
)/
'''


# This next section only exists for people that have their editors
# automatically call isort.
[tool.isort]
combine_as_imports = true
default_section = "THIRDPARTY"
force_grid_wrap = 0
force_single_line = true
force_sort_within_sections = true
include_trailing_comma = true
known_deform = "deform"
known_first_party = "deformdemo"
known_pyramid = "colander,jinja2,plaster,pyramid,pyramid_layout,venusian,zope,transaction,pyramid_chameleon,Chameleon"
known_tests="flaky,selenium"
line_length = 79
lines_after_imports = 2
multi_line_output = 3
no_lines_before = "THIRDPARTY"
profile = "black"
sections = ["FUTURE","STDLIB","PYRAMID","DEFORM","THIRDPARTY","FIRSTPARTY","LOCALFOLDER","TESTS"]
